title: Privacy Manifesto
description: >-
  Privacy Manifesto.
baseurl: "/404PrivacyManifesto"
url: "https://404loopback.github.io"
lang: fr
timezone: Europe/Paris

remote_theme: renyuanz/leonids@leonids-jekyll
keywords: ["privacy", "blog", "manifesto"]

markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!--more-->"

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-polyglot
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localization:
  - assets
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - css
  - js
  - fonts
  - img
  - favicon.ico
  - favicon.png
parallel_localization: true

collections:
  manifestos:
    output: true
    permalink: /manifestos/:name/

header_pages:
  - index.md
  - about.md
  - manifestos.md

owner:
  name: "Privacy Manifesto"
  avatar: "leonids-logo.png"
  job: "Digital Rights Blog"
  bio:
  email:
  disqus-shortname:
  twitter:
  facebook:
  github: "404loopback"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: manifestos
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
