title: Privacy Manifesto
description: >-
  Blog Jekyll minimal et propre, prêt pour GitHub Pages.
baseurl: "/privacy-manifesto"
url: "https://404loopback.github.io"
lang: fr
timezone: Europe/Paris

remote_theme: b2a3e8/jekyll-theme-console

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-polyglot
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localization:
  - assets
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
parallel_localization: true

collections:
  manifestos:
    output: true
    permalink: /manifestos/:name/

header_pages:
  - index.md
  - about.md
  - manifestos.md

header_manifestos: true
header_manifestos_limit: 5

style: dark
listen_for_clients_preferred_style: true
footer: "© Privacy Manifesto"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: manifestos
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
